import { uint8 } from '../num'

// The order matters in fetchInstruction and execute.
export enum Mode {
  IMP = 0, // must be 0
  IMM,
  ZP,
  ZPX,
  ZPY,
  IZX,
  IZY,
  REL,
  ABS,
  ABX,
  ABY,
  IND,
}

type FakeInstruction = "_IRQ" | "_NMI"
export type Instruction = FakeInstruction | "ADC" | "AHX" | "ALR" | "ANC" | "AND" | "ARR" | "ASL" | "AXS" | "BCC" | "BCS" | "BEQ" | "BIT" | "BMI" | "BNE" | "BPL" | "BRK" | "BVC" | "BVS" | "CLC" | "CLD" | "CLI" | "CLV" | "CMP" | "CPX" | "CPY" | "DCP" | "DEC" | "DEX" | "DEY" | "EOR" | "INC" | "INX" | "INY" | "ISC" | "JMP" | "JSR" | "KIL" | "LAS" | "LAX" | "LDA" | "LDX" | "LDY" | "LSR" | "NOP" | "ORA" | "PHA" | "PHP" | "PLA" | "PLP" | "RLA" | "ROL" | "ROR" | "RRA" | "RTI" | "RTS" | "SAX" | "SBC" | "SEC" | "SED" | "SEI" | "SHX" | "SHY" | "SLO" | "SRE" | "STA" | "STX" | "STY" | "TAS" | "TAX" | "TAY" | "TSX" | "TXA" | "TXS" | "TYA" | "XAA"

export interface Opcode {
  op: uint8
  opcode: Instruction
  mode: Mode
  cycle: number
  extra: boolean
}

export const nmi: Opcode = {
  "op": 256,
  "opcode": "_NMI",
  "mode": Mode.IMP,
  "cycle": 7,
  "extra": false
}
export const irq: Opcode = {
  "op": 257,
  "opcode": "_IRQ",
  "mode": Mode.IMP,
  "cycle": 7,
  "extra": false
}

// JSON generated by tools/genops.py
export const opcodes: Array<Opcode> = [
  {
    "op": 0,
    "opcode": "BRK",
    "mode": Mode.IMP,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 1,
    "opcode": "ORA",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 2,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 3,
    "opcode": "SLO",
    "mode": Mode.IZX,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 4,
    "opcode": "NOP",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 5,
    "opcode": "ORA",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 6,
    "opcode": "ASL",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 7,
    "opcode": "SLO",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 8,
    "opcode": "PHP",
    "mode": Mode.IMP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 9,
    "opcode": "ORA",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 10,
    "opcode": "ASL",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 11,
    "opcode": "ANC",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 12,
    "opcode": "NOP",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 13,
    "opcode": "ORA",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 14,
    "opcode": "ASL",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 15,
    "opcode": "SLO",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 16,
    "opcode": "BPL",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 17,
    "opcode": "ORA",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 18,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 19,
    "opcode": "SLO",
    "mode": Mode.IZY,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 20,
    "opcode": "NOP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 21,
    "opcode": "ORA",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 22,
    "opcode": "ASL",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 23,
    "opcode": "SLO",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 24,
    "opcode": "CLC",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 25,
    "opcode": "ORA",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 26,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 27,
    "opcode": "SLO",
    "mode": Mode.ABY,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 28,
    "opcode": "NOP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 29,
    "opcode": "ORA",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 30,
    "opcode": "ASL",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 31,
    "opcode": "SLO",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 32,
    "opcode": "JSR",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 33,
    "opcode": "AND",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 34,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 35,
    "opcode": "RLA",
    "mode": Mode.IZX,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 36,
    "opcode": "BIT",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 37,
    "opcode": "AND",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 38,
    "opcode": "ROL",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 39,
    "opcode": "RLA",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 40,
    "opcode": "PLP",
    "mode": Mode.IMP,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 41,
    "opcode": "AND",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 42,
    "opcode": "ROL",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 43,
    "opcode": "ANC",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 44,
    "opcode": "BIT",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 45,
    "opcode": "AND",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 46,
    "opcode": "ROL",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 47,
    "opcode": "RLA",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 48,
    "opcode": "BMI",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 49,
    "opcode": "AND",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 50,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 51,
    "opcode": "RLA",
    "mode": Mode.IZY,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 52,
    "opcode": "NOP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 53,
    "opcode": "AND",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 54,
    "opcode": "ROL",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 55,
    "opcode": "RLA",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 56,
    "opcode": "SEC",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 57,
    "opcode": "AND",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 58,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 59,
    "opcode": "RLA",
    "mode": Mode.ABY,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 60,
    "opcode": "NOP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 61,
    "opcode": "AND",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 62,
    "opcode": "ROL",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 63,
    "opcode": "RLA",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 64,
    "opcode": "RTI",
    "mode": Mode.IMP,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 65,
    "opcode": "EOR",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 66,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 67,
    "opcode": "SRE",
    "mode": Mode.IZX,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 68,
    "opcode": "NOP",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 69,
    "opcode": "EOR",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 70,
    "opcode": "LSR",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 71,
    "opcode": "SRE",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 72,
    "opcode": "PHA",
    "mode": Mode.IMP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 73,
    "opcode": "EOR",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 74,
    "opcode": "LSR",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 75,
    "opcode": "ALR",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 76,
    "opcode": "JMP",
    "mode": Mode.ABS,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 77,
    "opcode": "EOR",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 78,
    "opcode": "LSR",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 79,
    "opcode": "SRE",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 80,
    "opcode": "BVC",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 81,
    "opcode": "EOR",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 82,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 83,
    "opcode": "SRE",
    "mode": Mode.IZY,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 84,
    "opcode": "NOP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 85,
    "opcode": "EOR",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 86,
    "opcode": "LSR",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 87,
    "opcode": "SRE",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 88,
    "opcode": "CLI",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 89,
    "opcode": "EOR",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 90,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 91,
    "opcode": "SRE",
    "mode": Mode.ABY,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 92,
    "opcode": "NOP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 93,
    "opcode": "EOR",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 94,
    "opcode": "LSR",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 95,
    "opcode": "SRE",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 96,
    "opcode": "RTS",
    "mode": Mode.IMP,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 97,
    "opcode": "ADC",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 98,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 99,
    "opcode": "RRA",
    "mode": Mode.IZX,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 100,
    "opcode": "NOP",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 101,
    "opcode": "ADC",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 102,
    "opcode": "ROR",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 103,
    "opcode": "RRA",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 104,
    "opcode": "PLA",
    "mode": Mode.IMP,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 105,
    "opcode": "ADC",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 106,
    "opcode": "ROR",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 107,
    "opcode": "ARR",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 108,
    "opcode": "JMP",
    "mode": Mode.IND,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 109,
    "opcode": "ADC",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 110,
    "opcode": "ROR",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 111,
    "opcode": "RRA",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 112,
    "opcode": "BVS",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 113,
    "opcode": "ADC",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 114,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 115,
    "opcode": "RRA",
    "mode": Mode.IZY,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 116,
    "opcode": "NOP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 117,
    "opcode": "ADC",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 118,
    "opcode": "ROR",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 119,
    "opcode": "RRA",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 120,
    "opcode": "SEI",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 121,
    "opcode": "ADC",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 122,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 123,
    "opcode": "RRA",
    "mode": Mode.ABY,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 124,
    "opcode": "NOP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 125,
    "opcode": "ADC",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 126,
    "opcode": "ROR",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 127,
    "opcode": "RRA",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 128,
    "opcode": "NOP",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 129,
    "opcode": "STA",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 130,
    "opcode": "NOP",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 131,
    "opcode": "SAX",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 132,
    "opcode": "STY",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 133,
    "opcode": "STA",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 134,
    "opcode": "STX",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 135,
    "opcode": "SAX",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 136,
    "opcode": "DEY",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 137,
    "opcode": "NOP",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 138,
    "opcode": "TXA",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 139,
    "opcode": "XAA",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 140,
    "opcode": "STY",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 141,
    "opcode": "STA",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 142,
    "opcode": "STX",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 143,
    "opcode": "SAX",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 144,
    "opcode": "BCC",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 145,
    "opcode": "STA",
    "mode": Mode.IZY,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 146,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 147,
    "opcode": "AHX",
    "mode": Mode.IZY,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 148,
    "opcode": "STY",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 149,
    "opcode": "STA",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 150,
    "opcode": "STX",
    "mode": Mode.ZPY,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 151,
    "opcode": "SAX",
    "mode": Mode.ZPY,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 152,
    "opcode": "TYA",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 153,
    "opcode": "STA",
    "mode": Mode.ABY,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 154,
    "opcode": "TXS",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 155,
    "opcode": "TAS",
    "mode": Mode.ABY,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 156,
    "opcode": "SHY",
    "mode": Mode.ABX,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 157,
    "opcode": "STA",
    "mode": Mode.ABX,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 158,
    "opcode": "SHX",
    "mode": Mode.ABY,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 159,
    "opcode": "AHX",
    "mode": Mode.ABY,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 160,
    "opcode": "LDY",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 161,
    "opcode": "LDA",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 162,
    "opcode": "LDX",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 163,
    "opcode": "LAX",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 164,
    "opcode": "LDY",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 165,
    "opcode": "LDA",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 166,
    "opcode": "LDX",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 167,
    "opcode": "LAX",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 168,
    "opcode": "TAY",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 169,
    "opcode": "LDA",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 170,
    "opcode": "TAX",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 171,
    "opcode": "LAX",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 172,
    "opcode": "LDY",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 173,
    "opcode": "LDA",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 174,
    "opcode": "LDX",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 175,
    "opcode": "LAX",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 176,
    "opcode": "BCS",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 177,
    "opcode": "LDA",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 178,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 179,
    "opcode": "LAX",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 180,
    "opcode": "LDY",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 181,
    "opcode": "LDA",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 182,
    "opcode": "LDX",
    "mode": Mode.ZPY,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 183,
    "opcode": "LAX",
    "mode": Mode.ZPY,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 184,
    "opcode": "CLV",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 185,
    "opcode": "LDA",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 186,
    "opcode": "TSX",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 187,
    "opcode": "LAS",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 188,
    "opcode": "LDY",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 189,
    "opcode": "LDA",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 190,
    "opcode": "LDX",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 191,
    "opcode": "LAX",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 192,
    "opcode": "CPY",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 193,
    "opcode": "CMP",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 194,
    "opcode": "NOP",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 195,
    "opcode": "DCP",
    "mode": Mode.IZX,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 196,
    "opcode": "CPY",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 197,
    "opcode": "CMP",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 198,
    "opcode": "DEC",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 199,
    "opcode": "DCP",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 200,
    "opcode": "INY",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 201,
    "opcode": "CMP",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 202,
    "opcode": "DEX",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 203,
    "opcode": "AXS",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 204,
    "opcode": "CPY",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 205,
    "opcode": "CMP",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 206,
    "opcode": "DEC",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 207,
    "opcode": "DCP",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 208,
    "opcode": "BNE",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 209,
    "opcode": "CMP",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 210,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 211,
    "opcode": "DCP",
    "mode": Mode.IZY,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 212,
    "opcode": "NOP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 213,
    "opcode": "CMP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 214,
    "opcode": "DEC",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 215,
    "opcode": "DCP",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 216,
    "opcode": "CLD",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 217,
    "opcode": "CMP",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 218,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 219,
    "opcode": "DCP",
    "mode": Mode.ABY,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 220,
    "opcode": "NOP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 221,
    "opcode": "CMP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 222,
    "opcode": "DEC",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 223,
    "opcode": "DCP",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 224,
    "opcode": "CPX",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 225,
    "opcode": "SBC",
    "mode": Mode.IZX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 226,
    "opcode": "NOP",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 227,
    "opcode": "ISC",
    "mode": Mode.IZX,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 228,
    "opcode": "CPX",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 229,
    "opcode": "SBC",
    "mode": Mode.ZP,
    "cycle": 3,
    "extra": false
  },
  {
    "op": 230,
    "opcode": "INC",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 231,
    "opcode": "ISC",
    "mode": Mode.ZP,
    "cycle": 5,
    "extra": false
  },
  {
    "op": 232,
    "opcode": "INX",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 233,
    "opcode": "SBC",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 234,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 235,
    "opcode": "SBC",
    "mode": Mode.IMM,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 236,
    "opcode": "CPX",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 237,
    "opcode": "SBC",
    "mode": Mode.ABS,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 238,
    "opcode": "INC",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 239,
    "opcode": "ISC",
    "mode": Mode.ABS,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 240,
    "opcode": "BEQ",
    "mode": Mode.REL,
    "cycle": 2,
    "extra": true
  },
  {
    "op": 241,
    "opcode": "SBC",
    "mode": Mode.IZY,
    "cycle": 5,
    "extra": true
  },
  {
    "op": 242,
    "opcode": "KIL",
    "mode": Mode.IMP,
    "cycle": 0,
    "extra": false
  },
  {
    "op": 243,
    "opcode": "ISC",
    "mode": Mode.IZY,
    "cycle": 8,
    "extra": false
  },
  {
    "op": 244,
    "opcode": "NOP",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 245,
    "opcode": "SBC",
    "mode": Mode.ZPX,
    "cycle": 4,
    "extra": false
  },
  {
    "op": 246,
    "opcode": "INC",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 247,
    "opcode": "ISC",
    "mode": Mode.ZPX,
    "cycle": 6,
    "extra": false
  },
  {
    "op": 248,
    "opcode": "SED",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 249,
    "opcode": "SBC",
    "mode": Mode.ABY,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 250,
    "opcode": "NOP",
    "mode": Mode.IMP,
    "cycle": 2,
    "extra": false
  },
  {
    "op": 251,
    "opcode": "ISC",
    "mode": Mode.ABY,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 252,
    "opcode": "NOP",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 253,
    "opcode": "SBC",
    "mode": Mode.ABX,
    "cycle": 4,
    "extra": true
  },
  {
    "op": 254,
    "opcode": "INC",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
  {
    "op": 255,
    "opcode": "ISC",
    "mode": Mode.ABX,
    "cycle": 7,
    "extra": false
  },
]
