import { uint8 } from '../num'

// The order matters in fetchInstruction and execute.
export enum Mode {
  IMP = 0, // must be 0
  IMM,
  ZP,
  ZPX,
  ZPY,
  IZX,
  IZY,
  REL,
  ABS,
  ABX,
  ABY,
  IND,
}

export enum Instruction {
  ADC,
  AHX,
  ALR,
  ANC,
  AND,
  ARR,
  ASL,
  AXS,
  BCC,
  BCS,
  BEQ,
  BIT,
  BMI,
  BNE,
  BPL,
  BRK,
  BVC,
  BVS,
  CLC,
  CLD,
  CLI,
  CLV,
  CMP,
  CPX,
  CPY,
  DCP,
  DEC,
  DEX,
  DEY,
  EOR,
  INC,
  INX,
  INY,
  ISC,
  JMP,
  JSR,
  KIL,
  LAS,
  LAX,
  LDA,
  LDX,
  LDY,
  LSR,
  NOP,
  ORA,
  PHA,
  PHP,
  PLA,
  PLP,
  RLA,
  ROL,
  ROR,
  RRA,
  RTI,
  RTS,
  SAX,
  SBC,
  SEC,
  SED,
  SEI,
  SHX,
  SHY,
  SLO,
  SRE,
  STA,
  STX,
  STY,
  TAS,
  TAX,
  TAY,
  TSX,
  TXA,
  TXS,
  TYA,
  XAA,
  _NMI, // NMI, IRQ are fake instructions
  _IRQ,
}

export interface Opcode {
  op: uint8
  opcode: Instruction
  mode: Mode
  cycle: number
  extra: boolean
}

export const nmi: Opcode = {
  op: 256,
  opcode: Instruction._NMI,
  mode: Mode.IMP,
  cycle: 7,
  extra: false
}
export const irq: Opcode = {
  op: 257,
  opcode: Instruction._IRQ,
  mode: Mode.IMP,
  cycle: 7,
  extra: false
}

// JSON generated by tools/genops.py
export const opcodes: Array<Opcode> = [
  {
    op: 0,
    opcode: Instruction.BRK,
    mode: Mode.IMP,
    cycle: 7,
    extra: false
  },
  {
    op: 1,
    opcode: Instruction.ORA,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 2,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 3,
    opcode: Instruction.SLO,
    mode: Mode.IZX,
    cycle: 8,
    extra: false
  },
  {
    op: 4,
    opcode: Instruction.NOP,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 5,
    opcode: Instruction.ORA,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 6,
    opcode: Instruction.ASL,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 7,
    opcode: Instruction.SLO,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 8,
    opcode: Instruction.PHP,
    mode: Mode.IMP,
    cycle: 3,
    extra: false
  },
  {
    op: 9,
    opcode: Instruction.ORA,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 10,
    opcode: Instruction.ASL,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 11,
    opcode: Instruction.ANC,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 12,
    opcode: Instruction.NOP,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 13,
    opcode: Instruction.ORA,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 14,
    opcode: Instruction.ASL,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 15,
    opcode: Instruction.SLO,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 16,
    opcode: Instruction.BPL,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 17,
    opcode: Instruction.ORA,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 18,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 19,
    opcode: Instruction.SLO,
    mode: Mode.IZY,
    cycle: 8,
    extra: false
  },
  {
    op: 20,
    opcode: Instruction.NOP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 21,
    opcode: Instruction.ORA,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 22,
    opcode: Instruction.ASL,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 23,
    opcode: Instruction.SLO,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 24,
    opcode: Instruction.CLC,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 25,
    opcode: Instruction.ORA,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 26,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 27,
    opcode: Instruction.SLO,
    mode: Mode.ABY,
    cycle: 7,
    extra: false
  },
  {
    op: 28,
    opcode: Instruction.NOP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 29,
    opcode: Instruction.ORA,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 30,
    opcode: Instruction.ASL,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 31,
    opcode: Instruction.SLO,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 32,
    opcode: Instruction.JSR,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 33,
    opcode: Instruction.AND,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 34,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 35,
    opcode: Instruction.RLA,
    mode: Mode.IZX,
    cycle: 8,
    extra: false
  },
  {
    op: 36,
    opcode: Instruction.BIT,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 37,
    opcode: Instruction.AND,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 38,
    opcode: Instruction.ROL,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 39,
    opcode: Instruction.RLA,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 40,
    opcode: Instruction.PLP,
    mode: Mode.IMP,
    cycle: 4,
    extra: false
  },
  {
    op: 41,
    opcode: Instruction.AND,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 42,
    opcode: Instruction.ROL,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 43,
    opcode: Instruction.ANC,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 44,
    opcode: Instruction.BIT,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 45,
    opcode: Instruction.AND,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 46,
    opcode: Instruction.ROL,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 47,
    opcode: Instruction.RLA,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 48,
    opcode: Instruction.BMI,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 49,
    opcode: Instruction.AND,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 50,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 51,
    opcode: Instruction.RLA,
    mode: Mode.IZY,
    cycle: 8,
    extra: false
  },
  {
    op: 52,
    opcode: Instruction.NOP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 53,
    opcode: Instruction.AND,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 54,
    opcode: Instruction.ROL,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 55,
    opcode: Instruction.RLA,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 56,
    opcode: Instruction.SEC,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 57,
    opcode: Instruction.AND,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 58,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 59,
    opcode: Instruction.RLA,
    mode: Mode.ABY,
    cycle: 7,
    extra: false
  },
  {
    op: 60,
    opcode: Instruction.NOP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 61,
    opcode: Instruction.AND,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 62,
    opcode: Instruction.ROL,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 63,
    opcode: Instruction.RLA,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 64,
    opcode: Instruction.RTI,
    mode: Mode.IMP,
    cycle: 6,
    extra: false
  },
  {
    op: 65,
    opcode: Instruction.EOR,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 66,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 67,
    opcode: Instruction.SRE,
    mode: Mode.IZX,
    cycle: 8,
    extra: false
  },
  {
    op: 68,
    opcode: Instruction.NOP,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 69,
    opcode: Instruction.EOR,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 70,
    opcode: Instruction.LSR,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 71,
    opcode: Instruction.SRE,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 72,
    opcode: Instruction.PHA,
    mode: Mode.IMP,
    cycle: 3,
    extra: false
  },
  {
    op: 73,
    opcode: Instruction.EOR,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 74,
    opcode: Instruction.LSR,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 75,
    opcode: Instruction.ALR,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 76,
    opcode: Instruction.JMP,
    mode: Mode.ABS,
    cycle: 3,
    extra: false
  },
  {
    op: 77,
    opcode: Instruction.EOR,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 78,
    opcode: Instruction.LSR,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 79,
    opcode: Instruction.SRE,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 80,
    opcode: Instruction.BVC,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 81,
    opcode: Instruction.EOR,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 82,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 83,
    opcode: Instruction.SRE,
    mode: Mode.IZY,
    cycle: 8,
    extra: false
  },
  {
    op: 84,
    opcode: Instruction.NOP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 85,
    opcode: Instruction.EOR,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 86,
    opcode: Instruction.LSR,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 87,
    opcode: Instruction.SRE,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 88,
    opcode: Instruction.CLI,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 89,
    opcode: Instruction.EOR,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 90,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 91,
    opcode: Instruction.SRE,
    mode: Mode.ABY,
    cycle: 7,
    extra: false
  },
  {
    op: 92,
    opcode: Instruction.NOP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 93,
    opcode: Instruction.EOR,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 94,
    opcode: Instruction.LSR,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 95,
    opcode: Instruction.SRE,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 96,
    opcode: Instruction.RTS,
    mode: Mode.IMP,
    cycle: 6,
    extra: false
  },
  {
    op: 97,
    opcode: Instruction.ADC,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 98,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 99,
    opcode: Instruction.RRA,
    mode: Mode.IZX,
    cycle: 8,
    extra: false
  },
  {
    op: 100,
    opcode: Instruction.NOP,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 101,
    opcode: Instruction.ADC,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 102,
    opcode: Instruction.ROR,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 103,
    opcode: Instruction.RRA,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 104,
    opcode: Instruction.PLA,
    mode: Mode.IMP,
    cycle: 4,
    extra: false
  },
  {
    op: 105,
    opcode: Instruction.ADC,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 106,
    opcode: Instruction.ROR,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 107,
    opcode: Instruction.ARR,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 108,
    opcode: Instruction.JMP,
    mode: Mode.IND,
    cycle: 5,
    extra: false
  },
  {
    op: 109,
    opcode: Instruction.ADC,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 110,
    opcode: Instruction.ROR,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 111,
    opcode: Instruction.RRA,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 112,
    opcode: Instruction.BVS,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 113,
    opcode: Instruction.ADC,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 114,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 115,
    opcode: Instruction.RRA,
    mode: Mode.IZY,
    cycle: 8,
    extra: false
  },
  {
    op: 116,
    opcode: Instruction.NOP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 117,
    opcode: Instruction.ADC,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 118,
    opcode: Instruction.ROR,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 119,
    opcode: Instruction.RRA,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 120,
    opcode: Instruction.SEI,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 121,
    opcode: Instruction.ADC,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 122,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 123,
    opcode: Instruction.RRA,
    mode: Mode.ABY,
    cycle: 7,
    extra: false
  },
  {
    op: 124,
    opcode: Instruction.NOP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 125,
    opcode: Instruction.ADC,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 126,
    opcode: Instruction.ROR,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 127,
    opcode: Instruction.RRA,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 128,
    opcode: Instruction.NOP,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 129,
    opcode: Instruction.STA,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 130,
    opcode: Instruction.NOP,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 131,
    opcode: Instruction.SAX,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 132,
    opcode: Instruction.STY,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 133,
    opcode: Instruction.STA,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 134,
    opcode: Instruction.STX,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 135,
    opcode: Instruction.SAX,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 136,
    opcode: Instruction.DEY,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 137,
    opcode: Instruction.NOP,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 138,
    opcode: Instruction.TXA,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 139,
    opcode: Instruction.XAA,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 140,
    opcode: Instruction.STY,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 141,
    opcode: Instruction.STA,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 142,
    opcode: Instruction.STX,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 143,
    opcode: Instruction.SAX,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 144,
    opcode: Instruction.BCC,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 145,
    opcode: Instruction.STA,
    mode: Mode.IZY,
    cycle: 6,
    extra: false
  },
  {
    op: 146,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 147,
    opcode: Instruction.AHX,
    mode: Mode.IZY,
    cycle: 6,
    extra: false
  },
  {
    op: 148,
    opcode: Instruction.STY,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 149,
    opcode: Instruction.STA,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 150,
    opcode: Instruction.STX,
    mode: Mode.ZPY,
    cycle: 4,
    extra: false
  },
  {
    op: 151,
    opcode: Instruction.SAX,
    mode: Mode.ZPY,
    cycle: 4,
    extra: false
  },
  {
    op: 152,
    opcode: Instruction.TYA,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 153,
    opcode: Instruction.STA,
    mode: Mode.ABY,
    cycle: 5,
    extra: false
  },
  {
    op: 154,
    opcode: Instruction.TXS,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 155,
    opcode: Instruction.TAS,
    mode: Mode.ABY,
    cycle: 5,
    extra: false
  },
  {
    op: 156,
    opcode: Instruction.SHY,
    mode: Mode.ABX,
    cycle: 5,
    extra: false
  },
  {
    op: 157,
    opcode: Instruction.STA,
    mode: Mode.ABX,
    cycle: 5,
    extra: false
  },
  {
    op: 158,
    opcode: Instruction.SHX,
    mode: Mode.ABY,
    cycle: 5,
    extra: false
  },
  {
    op: 159,
    opcode: Instruction.AHX,
    mode: Mode.ABY,
    cycle: 5,
    extra: false
  },
  {
    op: 160,
    opcode: Instruction.LDY,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 161,
    opcode: Instruction.LDA,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 162,
    opcode: Instruction.LDX,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 163,
    opcode: Instruction.LAX,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 164,
    opcode: Instruction.LDY,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 165,
    opcode: Instruction.LDA,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 166,
    opcode: Instruction.LDX,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 167,
    opcode: Instruction.LAX,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 168,
    opcode: Instruction.TAY,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 169,
    opcode: Instruction.LDA,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 170,
    opcode: Instruction.TAX,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 171,
    opcode: Instruction.LAX,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 172,
    opcode: Instruction.LDY,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 173,
    opcode: Instruction.LDA,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 174,
    opcode: Instruction.LDX,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 175,
    opcode: Instruction.LAX,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 176,
    opcode: Instruction.BCS,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 177,
    opcode: Instruction.LDA,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 178,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 179,
    opcode: Instruction.LAX,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 180,
    opcode: Instruction.LDY,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 181,
    opcode: Instruction.LDA,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 182,
    opcode: Instruction.LDX,
    mode: Mode.ZPY,
    cycle: 4,
    extra: false
  },
  {
    op: 183,
    opcode: Instruction.LAX,
    mode: Mode.ZPY,
    cycle: 4,
    extra: false
  },
  {
    op: 184,
    opcode: Instruction.CLV,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 185,
    opcode: Instruction.LDA,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 186,
    opcode: Instruction.TSX,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 187,
    opcode: Instruction.LAS,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 188,
    opcode: Instruction.LDY,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 189,
    opcode: Instruction.LDA,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 190,
    opcode: Instruction.LDX,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 191,
    opcode: Instruction.LAX,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 192,
    opcode: Instruction.CPY,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 193,
    opcode: Instruction.CMP,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 194,
    opcode: Instruction.NOP,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 195,
    opcode: Instruction.DCP,
    mode: Mode.IZX,
    cycle: 8,
    extra: false
  },
  {
    op: 196,
    opcode: Instruction.CPY,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 197,
    opcode: Instruction.CMP,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 198,
    opcode: Instruction.DEC,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 199,
    opcode: Instruction.DCP,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 200,
    opcode: Instruction.INY,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 201,
    opcode: Instruction.CMP,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 202,
    opcode: Instruction.DEX,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 203,
    opcode: Instruction.AXS,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 204,
    opcode: Instruction.CPY,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 205,
    opcode: Instruction.CMP,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 206,
    opcode: Instruction.DEC,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 207,
    opcode: Instruction.DCP,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 208,
    opcode: Instruction.BNE,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 209,
    opcode: Instruction.CMP,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 210,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 211,
    opcode: Instruction.DCP,
    mode: Mode.IZY,
    cycle: 8,
    extra: false
  },
  {
    op: 212,
    opcode: Instruction.NOP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 213,
    opcode: Instruction.CMP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 214,
    opcode: Instruction.DEC,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 215,
    opcode: Instruction.DCP,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 216,
    opcode: Instruction.CLD,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 217,
    opcode: Instruction.CMP,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 218,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 219,
    opcode: Instruction.DCP,
    mode: Mode.ABY,
    cycle: 7,
    extra: false
  },
  {
    op: 220,
    opcode: Instruction.NOP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 221,
    opcode: Instruction.CMP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 222,
    opcode: Instruction.DEC,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 223,
    opcode: Instruction.DCP,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 224,
    opcode: Instruction.CPX,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 225,
    opcode: Instruction.SBC,
    mode: Mode.IZX,
    cycle: 6,
    extra: false
  },
  {
    op: 226,
    opcode: Instruction.NOP,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 227,
    opcode: Instruction.ISC,
    mode: Mode.IZX,
    cycle: 8,
    extra: false
  },
  {
    op: 228,
    opcode: Instruction.CPX,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 229,
    opcode: Instruction.SBC,
    mode: Mode.ZP,
    cycle: 3,
    extra: false
  },
  {
    op: 230,
    opcode: Instruction.INC,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 231,
    opcode: Instruction.ISC,
    mode: Mode.ZP,
    cycle: 5,
    extra: false
  },
  {
    op: 232,
    opcode: Instruction.INX,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 233,
    opcode: Instruction.SBC,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 234,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 235,
    opcode: Instruction.SBC,
    mode: Mode.IMM,
    cycle: 2,
    extra: false
  },
  {
    op: 236,
    opcode: Instruction.CPX,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 237,
    opcode: Instruction.SBC,
    mode: Mode.ABS,
    cycle: 4,
    extra: false
  },
  {
    op: 238,
    opcode: Instruction.INC,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 239,
    opcode: Instruction.ISC,
    mode: Mode.ABS,
    cycle: 6,
    extra: false
  },
  {
    op: 240,
    opcode: Instruction.BEQ,
    mode: Mode.REL,
    cycle: 2,
    extra: true
  },
  {
    op: 241,
    opcode: Instruction.SBC,
    mode: Mode.IZY,
    cycle: 5,
    extra: true
  },
  {
    op: 242,
    opcode: Instruction.KIL,
    mode: Mode.IMP,
    cycle: 0,
    extra: false
  },
  {
    op: 243,
    opcode: Instruction.ISC,
    mode: Mode.IZY,
    cycle: 8,
    extra: false
  },
  {
    op: 244,
    opcode: Instruction.NOP,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 245,
    opcode: Instruction.SBC,
    mode: Mode.ZPX,
    cycle: 4,
    extra: false
  },
  {
    op: 246,
    opcode: Instruction.INC,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 247,
    opcode: Instruction.ISC,
    mode: Mode.ZPX,
    cycle: 6,
    extra: false
  },
  {
    op: 248,
    opcode: Instruction.SED,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 249,
    opcode: Instruction.SBC,
    mode: Mode.ABY,
    cycle: 4,
    extra: true
  },
  {
    op: 250,
    opcode: Instruction.NOP,
    mode: Mode.IMP,
    cycle: 2,
    extra: false
  },
  {
    op: 251,
    opcode: Instruction.ISC,
    mode: Mode.ABY,
    cycle: 7,
    extra: false
  },
  {
    op: 252,
    opcode: Instruction.NOP,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 253,
    opcode: Instruction.SBC,
    mode: Mode.ABX,
    cycle: 4,
    extra: true
  },
  {
    op: 254,
    opcode: Instruction.INC,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
  {
    op: 255,
    opcode: Instruction.ISC,
    mode: Mode.ABX,
    cycle: 7,
    extra: false
  },
]
