# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Upload test results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: checkout submodules
      run: git submodule update --init --force --recursive
    - name: Use Node.js v16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npx ts-node ./src/testing/ci/golden_gen.node.ts --upload
      env:
        FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
